### PR TITLE
Fix indentation

### PR DESCRIPTION
**Pull request by tarsius**

### CODE REVIEW

**Comment by tarsius** [comment]
Friendly ping :smile:

**Comment by tarsius** [comment]
Closing because this fixes a minor issue and the author hasn't pushed any commits to any repository on Github for a few years, so it is unlikely they will return to deal with this.

**Comment by atomontage** [comment]
Sorry for delay, RL caught up with me. Hopefully I can start being active here again.

**Comment by tarsius** [comment]
Ah, I should have been a *bit* more patient after the ping. :grinning: 

Thanks!

**Pull request merged**
